name: naver_crs
description: A resource to help developers evaluate and use Flutter.
repository: https://github.com/flutter/gallery
version: 0.0.1+000002

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore

environment:
  flutter: ^2.2.0
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  get:
  adaptive_breakpoints: ^0.1.0
  animations: ^2.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter_gallery_assets: ^1.0.2
  flutter_localized_locales: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^2.0.0
  meta: ^1.3.0
  package_info_plus: ^1.0.1
  provider: ^6.0.0
  rally_assets: ^3.0.1
  scoped_model: ^2.0.0-nullsafety.0
  shrine_images: ^2.0.1
  url_launcher: ^6.0.3
  vector_math: ^2.1.0
  flutter_svg: ^0.22.0
  form_field_validator: ^1.1.0
  google_nav_bar: ^5.0.5
  lottie: ^1.2.1
  share: ^2.0.4
  flutter_share: ^2.0.0
  screenshot: ^1.2.3
  file_picker: ^4.1.3
  flutter_gradient_colors: ^2.1.1
  sweetalertv2: any
  flutter_countdown_timer: ^4.1.0
  http: ^0.13.4
  convert: ^3.0.1
  camera: ^0.9.4+3
  editable: ^2.0.0
  pdf: ^3.6.1
  vimeo_player_flutter: ^0.0.3+1
  flutter_html: ^2.1.5
  flutter_signature_pad: ^3.0.0
  datetime_picker_formfield: ^2.0.0
  carousel_slider: ^4.0.0
  checkbox_formfield: ^0.1.1
  radio_button_form_field: ^0.0.4
  property_change_notifier: ^0.3.0
  multi_select_flutter: ^4.0.0
  flutter_swiper: ^1.1.6
  modal_bottom_sheet: ^2.0.0
  printing: ^5.6.6
  youtube_player_iframe: ^2.2.2
  youtube_player_flutter: ^8.0.0
  multiselect: ^0.0.4
  flutter_hooks: ^0.18.2+1
  dropdown_formfield: ^0.1.4
  web_browser: ^0.5.0
  flutter_inappwebview: ^5.3.2
  counter: ^0.2.2
  flutter_week_view: ^1.2.1+1
  interval_time_picker: ^1.0.0+3
  time_range_picker: ^2.1.0
  multiselect_formfield: ^0.1.7
  syncfusion_flutter_calendar: ^20.1.50
  tutorial_coach_mark: ^1.2.3
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  shelf_router: ^1.1.2
  dropdown_search: ^5.0.2
  # image_picker: ^0.8.4+4
  # image_picker_for_web: ^2.1.4

dev_dependencies:
  flutter_launcher_icons:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.2
  grinder: ^0.9.0
  path: ^1.8.0
  pedantic: ^1.11.0
  string_scanner: ^1.1.0
  test: ^1.16.8
  web_benchmarks: ^0.0.5

flutter:
  # deferred-components:
  #   - name: crane
  #     libraries:
  #       # Only one library from the loading unit is necessary.
  #       - package:gallery/studies/crane/app.dart
  #     assets:
  #       - lib/assets
  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/images/1x/
    - assets/images/0.5x/
    - assets/images/0.75x/

  generate: true
  uses-material-design: true
  # fonts:
  #   - family: GalleryIcons
  #     fonts:
  #       - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
flutter_localizations:
  sdk: flutter
  intl: 0.16.1

flutter_intl:
  enabled: true

flutter_icons:
  android: "icon"
  ios: false
  image_path_ios: "assets/images/1x/icon.png"
  image_path_android: "assets/images/1x/icon.png"
  adaptive_icon_background: "assets/images/1x/icon.png"
  adaptive_icon_foreground: "assets/images/1x/icon.png"
